[package]
name = "clewdr"
version = "0.6.0"
edition = "2024"
authors = ["Xerxes-2"]

[lib]
path = "src/lib/lib.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
rquest = { version = "5", features = [
    "json",
    "stream",
    "multipart",
    "socks",
    "cookies",
    "charset",
] }
rquest-util = "2"
serde_json = "1"
const_format = { version = "0.2", features = ["fmt"] }
figlet-rs = "0.1"
serde = { version = "1", features = ["derive"] }
colored = "3"
axum = { version = "0.8", features = [
    "json",
    "tracing",
    "tokio",
    "macros",
    "http2",
] }
regex = "1"
tracing = { version = "0.1", features = [
    "max_level_debug",
    "release_max_level_info",
] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "chrono"] }
rand = "0.9"
chrono = "0.4"
futures = "0.3"
thiserror = "2"
uuid = { version = "1", features = ["v4"] }
clap = { version = "4", features = ["derive"] }
async-trait = "0.1"
futures-util = "0.3"
base64 = "0.22"
itertools = "0.14"
scopeguard = "1.2"
toml = "0.8"
eventsource-stream = "0.2"
url = "2"
enable-ansi-support = "0.2"
tracing-appender = "0.2"
self-replace = "1"
zip = "2"
tempfile = "3"
transform-stream = "0.3"
axum-auth = "0.8"
tiktoken-rs = "0.6"
passwords = "3"
tower-http = { version = "0.6", features = ["fs", "trace"] }
walkdir = "2"
figment = { version = "0.10", features = ["env", "json", "toml"] }
